function p=LBA_cdf(t,A,b,v,sdv)
%Basic numerical integration of the pdf generated by LBA. Much quicker than
%using quad or romberg and accurate.

p=zeros(length(t),1);
pdf=LBA_pdf([1:ceil(max(t))]',A,b,v,sdv);
cdf=cumsum(pdf);
for i=1:length(t)
    if(mod(t(i),1)>0) %if latency is not an integer, linearly interpolate
        p(i,1)=cdf(floor(t(i)))+(cdf(ceil(t(i)))-cdf(floor(t(i))))*mod(t(i),1);
    else p(i,1)=cdf(t(i));
    end
end